data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  AzureWebJobsFeatureFlags: RW5hYmxlV29ya2VySW5kZXhpbmc=
  AzureWebJobsStorage: ''
  CosmosDbConnection: bW9uZ29kYjovL25laWdoYm9ybHktY29zbW9zZGI6Vm95TjQ1cVpueGNzQjlZRkFiYm9GelR4SHpKaVpNbVl4WXFDTWIwdDJENXNIZFJTRUJKS1VMa2JEVHVydzRhTDNwQmNWNHBSMDd6YUFDRGIwRDBtY2c9PUBuZWlnaGJvcmx5LWNvc21vc2RiLm1vbmdvLmNvc21vcy5henVyZS5jb206MTAyNTUvP3NzbD10cnVlJnJlcGxpY2FTZXQ9Z2xvYmFsZGImcmV0cnl3cml0ZXM9ZmFsc2UmbWF4SWRsZVRpbWVNUz0xMjAwMDAmYXBwTmFtZT1AbmVpZ2hib3JseS1jb3Ntb3NkYkA=
apiVersion: v1
kind: Secret
metadata:
  name: neighborlyfunction
---
data:
  host.master: czk1X09XNndUUTlMNU1yeVZEcHVKNV94dFNYakJCWFkwRlY2ZEhuMzRXVWtBekZ1UTg2bjd3PT0=
  host.function.default: cEF3dDE1alZaQmZaeE9meFNaNWw3cXRRS21aSG5YbFVhU25TOVpTZzlrMGRBekZ1ZC1jdHRRPT0=
  host.systemKey.default: MmtfN0h4ZHBMS3lEeUhKTGZ3MGJNOVVsQXBPWVlvU3E2X2NHOHBtaFRnT3dBekZ1ZFBwNUV3PT0=
  functions.deleteadvertisement.default: b0swbmpUMVlQMWUyUU10eHR5SHdwVU5PZ2NmSWhOY3ZvVEIzX2NRUE13WU9BekZ1ZmlnUUdnPT0=
  functions.getpost.default: TnVKNm1Sd3JXWnliSFdBUW91MmhBVVkzUmZEeWNJTmI5UTFtakRpdWx1NHdBekZ1MVVnSS1nPT0=
  functions.getadvertisement.default: MFZyR2dLaTljZXNKd29vVGUwT0ZsWUM2RzRQWldrMkoxQ1paYXBnNU5RaExBekZ1RG81d2hRPT0=
  functions.createadvertisement.default: b3FHVUhhTVA2VFVpU2hLbGRyaWszczRNRjB3RFBtZGtyM0NMejFwVTNJUzJBekZ1amJVRGl3PT0=
  functions.getadvertisements.default: T2MwbjBKUkhSX3NMaGQ2anhlSlpSSF9xaEF1c01vVWdwMlFZOFdiQ0pyWk5BekZ1ZUFWb1B3PT0=
  functions.updateadvertisement.default: R2JpUjFoUlh6YUNqNTFWbVRnbHZuZ3czVmk3OFdCVThVTkpIcWdJbzdhaGRBekZ1V1g3NlB3PT0=
  functions.getposts.default: eDZmck5uV1kxdU52ckNESWN0VHRta1JjSkxod3NDSnNvdWM4MmctMFhkTWRBekZ1eWRTUzN3PT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-neighborlyfunction
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neighborlyfunction-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: neighborlyfunction-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neighborlyfunction-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: neighborlyfunction-http
spec:
  selector:
    app: neighborlyfunction-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborlyfunction-http
  labels:
    app: neighborlyfunction-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neighborlyfunction-http
  template:
    metadata:
      labels:
        app: neighborlyfunction-http
    spec:
      containers:
      - name: neighborlyfunction-http
        image: neighborlyregistry/neighborlyfunction:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: getPost
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__4
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__5
          value: updateAdvertisement
        - name: AzureFunctionsJobHost__functions__6
          value: getPosts
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-neighborlyfunction
        envFrom:
        - secretRef:
            name: neighborlyfunction
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborlyfunction-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neighborlyfunction
  labels:
    app: neighborlyfunction
spec:
  selector:
    matchLabels:
      app: neighborlyfunction
  template:
    metadata:
      labels:
        app: neighborlyfunction
    spec:
      containers:
      - name: neighborlyfunction
        image: neighborlyregistry/neighborlyfunction:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventGridTrigger
        envFrom:
        - secretRef:
            name: neighborlyfunction
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: neighborlyfunction-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: neighborlyfunction
  labels: {}
spec:
  scaleTargetRef:
    name: neighborlyfunction
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
---

